#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
name = "zenoh_backend_s3"
version = "0.6.0-dev.0"
authors = [
    "kydos <angelo@icorsaro.net>",
    "Julien Enoch <julien@enoch.fr>",
    "Olivier Hécart <olivier.hecart@zettascale.tech>",
    "Luca Cominardi <luca.cominardi@zettascale.tech>",
]
edition = "2018"

[lib]
name = "zbackend_s3"
crate-type = ["cdylib"]

[dependencies]
zenoh_backend_traits = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes"}
zenoh-buffers = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh-core = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh-protocol = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh-collections = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh-util = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
async-std = { version = "=1.12.0", default-features = false, features = [
    "unstable",
	"tokio1",
] }
async-trait = "0.1.42"
env_logger = "0.9.0"
git-version = "0.3.4"
http = "0.2.8"
lazy_static = "1.4.0"
log = "0.4"
serde_json = "1.0"
aws-config = "0.49.0"
aws-sdk-s3 = "0.19.0"
aws-smithy-http = "0.49.0"
aws-types = "0.49.0"
tokio = { version = "1", features = ["full"] }
uhlc = "0.4.0"

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.deb]
name = "zenoh-backend-s3"
maintainer = "zenoh-dev@eclipse.org"
copyright = "2022 ZettaScale Technology"
section = "net"
license-file = ["LICENSE", "0"]
depends = "zenoh-plugin-storage-manager (=0.6.0~dev.0)"
